# Linear Regression on Time Series with SciKit Learn and Pandas

This notebook demonstrates linear regression using 

* scikit learn
* pandas
* numpy

## Imports

Import the required libraries, like so.

In [1]:
import numpy as np
import pandas as pd
import datetime

## Create time series data

There are many ways to do this. Refer to the [Time series](https://pandas.pydata.org/docs/getting_started/10min.html#time-series) section in the pandas documentation for more details.

Here, we take a date range for the year of 2020 and create a datetime index based on each day.

In [2]:
start = datetime.datetime(2020, 1, 1)
end = datetime.datetime(2020, 12, 31)
index = pd.date_range(start, end)
index, len(index)

(DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
                '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
                '2020-01-09', '2020-01-10',
                ...
                '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25',
                '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
                '2020-12-30', '2020-12-31'],
               dtype='datetime64[ns]', length=366, freq='D'), 366)

## Create a pandas dataframe out of that

Next, we can put this in a pandas dataframe. We can add an artificial "value" column that is a multiple of 5 for some generic target data.

In [3]:
multiple = 5
l = list(range(0, len(index)*multiple, multiple))
df = pd.DataFrame(l, index = index)
df.index.name = "date"
df.columns = ["value"]
df

            value
date
2020-01-01      0
2020-01-02      5
2020-01-03     10
2020-01-04     15
2020-01-05     20
...           ...
2020-12-27   1805
2020-12-28   1810
2020-12-29   1815
2020-12-30   1820
2020-12-31   1825

[366 rows x 1 columns]

## Simple feature engineering from time series

We want something sensible to predict from. One simple option is to convert the date index into an integer from the minimum start date like so:

In [4]:
df['days_from_start'] = (df.index - df.index[0]).days; df

            value  days_from_start
date
2020-01-01      0                0
2020-01-02      5                1
2020-01-03     10                2
2020-01-04     15                3
2020-01-05     20                4
...           ...              ...
2020-12-27   1805              361
2020-12-28   1810              362
2020-12-29   1815              363
2020-12-30   1820              364
2020-12-31   1825              365

[366 rows x 2 columns]

## Simple Regression

We can now pull out the columns for simple linear regression.

In [5]:
x = df['days_from_start'].values
y = df['value'].values
x, y

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
        182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
        195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
        208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
        247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
        260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
        273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
        286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
        299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
        312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
        325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
        338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
        351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
        364, 365]),
 array([   0,    5,   10,   15,   20,   25,   30,   35,   40,   45,   50,
          55,   60,   65,   70,   75,   80,   85,   90,   95,  100,  105,
         110,  115,  120,  125,  130,  135,  140,  145,  150,  155,  160,
         165,  170,  175,  180,  185,  190,  195,  200,  205,  210,  215,
         220,  225,  230,  235,  240,  245,  250,  255,  260,  265,  270,
         275,  280,  285,  290,  295,  300,  305,  310,  315,  320,  325,
         330,  335,  340,  345,  350,  355,  360,  365,  370,  375,  380,
         385,  390,  395,  400,  405,  410,  415,  420,  425,  430,  435,
         440,  445,  450,  455,  460,  465,  470,  475,  480,  485,  490,
         495,  500,  505,  510,  515,  520,  525,  530,  535,  540,  545,
         550,  555,  560,  565,  570,  575,  580,  585,  590,  595,  600,
         605,  610,  615,  620,  625,  630,  635,  640,  645,  650,  655,
         660,  665,  670,  675,  680,  685,  690,  695,  700,  705,  710,
         715,  720,  725,  730,  735,  740,  745,  750,  755,  760,  765,
         770,  775,  780,  785,  790,  795,  800,  805,  810,  815,  820,
         825,  830,  835,  840,  845,  850,  855,  860,  865,  870,  875,
         880,  885,  890,  895,  900,  905,  910,  915,  920,  925,  930,
         935,  940,  945,  950,  955,  960,  965,  970,  975,  980,  985,
         990,  995, 1000, 1005, 1010, 1015, 1020, 1025, 1030, 1035, 1040,
        1045, 1050, 1055, 1060, 1065, 1070, 1075, 1080, 1085, 1090, 1095,
        1100, 1105, 1110, 1115, 1120, 1125, 1130, 1135, 1140, 1145, 1150,
        1155, 1160, 1165, 1170, 1175, 1180, 1185, 1190, 1195, 1200, 1205,
        1210, 1215, 1220, 1225, 1230, 1235, 1240, 1245, 1250, 1255, 1260,
        1265, 1270, 1275, 1280, 1285, 1290, 1295, 1300, 1305, 1310, 1315,
        1320, 1325, 1330, 1335, 1340, 1345, 1350, 1355, 1360, 1365, 1370,
        1375, 1380, 1385, 1390, 1395, 1400, 1405, 1410, 1415, 1420, 1425,
        1430, 1435, 1440, 1445, 1450, 1455, 1460, 1465, 1470, 1475, 1480,
        1485, 1490, 1495, 1500, 1505, 1510, 1515, 1520, 1525, 1530, 1535,
        1540, 1545, 1550, 1555, 1560, 1565, 1570, 1575, 1580, 1585, 1590,
        1595, 1600, 1605, 1610, 1615, 1620, 1625, 1630, 1635, 1640, 1645,
        1650, 1655, 1660, 1665, 1670, 1675, 1680, 1685, 1690, 1695, 1700,
        1705, 1710, 1715, 1720, 1725, 1730, 1735, 1740, 1745, 1750, 1755,
        1760, 1765, 1770, 1775, 1780, 1785, 1790, 1795, 1800, 1805, 1810,
        1815, 1820, 1825]))

Note that our input variables x have to be reshaped for input to the model.

In [6]:
x = x.reshape(-1, 1); x

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
       [ 71],
       [ 72],
       [ 73],
       [ 74],
       [ 75],
       [ 76],
       [ 77],
       [ 78],
       [ 79],
       [ 80],
       [ 81],
       [ 82],
       [ 83],
       [ 84],
       [ 85],
       [ 86],
       [ 87],
       [ 88],
       [ 89],
       [ 90],
       [ 91],
       [ 92],
       [ 93],
       [ 94],
       [ 95],
       [ 96],
       [ 97],
       [ 98],
       [ 99],
       [100],
       [101],
       [102],
       [103],
       [104],
       [105],
       [106],
       [107],
       [108],
       [109],
       [110],
       [111],
       [112],
       [113],
       [114],
       [115],
       [116],
       [117],
       [118],
       [119],
       [120],
       [121],
       [122],
       [123],
       [124],
       [125],
       [126],
       [127],
       [128],
       [129],
       [130],
       [131],
       [132],
       [133],
       [134],
       [135],
       [136],
       [137],
       [138],
       [139],
       [140],
       [141],
       [142],
       [143],
       [144],
       [145],
       [146],
       [147],
       [148],
       [149],
       [150],
       [151],
       [152],
       [153],
       [154],
       [155],
       [156],
       [157],
       [158],
       [159],
       [160],
       [161],
       [162],
       [163],
       [164],
       [165],
       [166],
       [167],
       [168],
       [169],
       [170],
       [171],
       [172],
       [173],
       [174],
       [175],
       [176],
       [177],
       [178],
       [179],
       [180],
       [181],
       [182],
       [183],
       [184],
       [185],
       [186],
       [187],
       [188],
       [189],
       [190],
       [191],
       [192],
       [193],
       [194],
       [195],
       [196],
       [197],
       [198],
       [199],
       [200],
       [201],
       [202],
       [203],
       [204],
       [205],
       [206],
       [207],
       [208],
       [209],
       [210],
       [211],
       [212],
       [213],
       [214],
       [215],
       [216],
       [217],
       [218],
       [219],
       [220],
       [221],
       [222],
       [223],
       [224],
       [225],
       [226],
       [227],
       [228],
       [229],
       [230],
       [231],
       [232],
       [233],
       [234],
       [235],
       [236],
       [237],
       [238],
       [239],
       [240],
       [241],
       [242],
       [243],
       [244],
       [245],
       [246],
       [247],
       [248],
       [249],
       [250],
       [251],
       [252],
       [253],
       [254],
       [255],
       [256],
       [257],
       [258],
       [259],
       [260],
       [261],
       [262],
       [263],
       [264],
       [265],
       [266],
       [267],
       [268],
       [269],
       [270],
       [271],
       [272],
       [273],
       [274],
       [275],
       [276],
       [277],
       [278],
       [279],
       [280],
       [281],
       [282],
       [283],
       [284],
       [285],
       [286],
       [287],
       [288],
       [289],
       [290],
       [291],
       [292],
       [293],
       [294],
       [295],
       [296],
       [297],
       [298],
       [299],
       [300],
       [301],
       [302],
       [303],
       [304],
       [305],
       [306],
       [307],
       [308],
       [309],
       [310],
       [311],
       [312],
       [313],
       [314],
       [315],
       [316],
       [317],
       [318],
       [319],
       [320],
       [321],
       [322],
       [323],
       [324],
       [325],
       [326],
       [327],
       [328],
       [329],
       [330],
       [331],
       [332],
       [333],
       [334],
       [335],
       [336],
       [337],
       [338],
       [339],
       [340],
       [341],
       [342],
       [343],
       [344],
       [345],
       [346],
       [347],
       [348],
       [349],
       [350],
       [351],
       [352],
       [353],
       [354],
       [355],
       [356],
       [357],
       [358],
       [359],
       [360],
       [361],
       [362],
       [363],
       [364],
       [365]])

In [7]:
from sklearn import linear_model
model = linear_model.LinearRegression().fit(x, y)
linear_model.LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
model.predict([[1], [7], [50]])

array([  5.,  35., 250.])